---
server:
  port: 8763
spring:
  profiles: client1
  application:
    name: eureka-client
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/
#      defaultZone: http://eureka.springcloud.cn/eureka/

---
server:
  port: 8764
spring:
  profiles: client2
  application:
    name: eureka-client
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/
#      defaultZone: http://eureka.springcloud.cn/eureka/
