server:
  port: 8765
spring:
  application:
    name: eureka-ribbon-client

eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/
#      defaultZone: http://eureka.springcloud.cn/eureka/

# 指定接收 hystrix dashbox 服务监控信息url路径
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
      base-path: /