---
server:
  port: 8767
spring:
  application:
    name: eureka-feign-client
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/
#      defaultZone: http://eureka.springcloud.cn/eureka/
feign:
  hystrix:
    enabled: true

# 指定接收 hystrix dashbox 服务监控信息url路径
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
      base-path: /
