---
server:
  port: 8767
spring:
  application:
    name: eureka-feign-client
eureka:
  client:
    serviceUrl:
#      defaultZone: http://peer1:8761/eureka/
      defaultZone: http://eureka.springcloud.cn/eureka/
